### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ghost** [shadow-workers/shadow-workers#6]
Do not quite understand the generation of sw and trigger by xss，
Can you write a presentation or tutorial that is easy to understand?

**Comment by clod81** [comment]
Hey, please refer to https://shadow-workers.github.io for setup guide.
The SW can be grabbed from `https://C2_HOST/modules/sw.js` and has to be uploaded on the vulnerable application.
The XSS example payload you can use is: `https://C2_HOST/modules/xss`.

**Comment by clod81** [comment]
https://www.trustedsec.com/blog/persistence-through-service-workers-part-1-introduction-and-target-application-setup
